<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('business_information', function (Blueprint $table) {
            $table->id();
            $table->string('coverage_info')->nullable();
            $table->string('month_business_salt')->nullable();
            $table->string('month_business_flour')->nullable();
            $table->string('month_business_oil')->nullable();
            $table->string('month_business_rice')->nullable();
            $table->string('month_business_pulse')->nullable();
            $table->string('month_business_tea')->nullable();
            $table->string('month_business_dairy')->nullable();
            $table->string('month_business')->nullable();
            $table->string('comm_earnings')->nullable();
            $table->string('vehicle_prod')->nullable();
            $table->string('sr_productivity')->nullable();
            $table->string('urban_wetmarket_grocer')->nullable();
            $table->string('urban_neighborhood_grocer')->nullable();
            $table->string('urban_general_store')->nullable();
            $table->string('urban_cosmetic_store')->nullable();
            $table->string('confectionary')->nullable();
            $table->string('urban_retail_coverage')->nullable();
            $table->string('smmt')->nullable();
            $table->string('chemist_pharmacy')->nullable();
            $table->string('rural_grocer')->nullable();
            $table->string('tong_tea_stall')->nullable();
            $table->string('horeca')->nullable();
            $table->string('rural_retail_coverage')->nullable();
            $table->string('dd_institution')->nullable();
            $table->string('others_channel')->nullable();
            $table->string('route_wholesale')->nullable();
            $table->string('csm_route_ols')->nullable();
            $table->string('sd_coverage_ols')->nullable();
            $table->string('alt_coverage')->nullable();
            $table->string('direct_coverage')->nullable();
            $table->string('controlled_coverage')->nullable();
            $table->integer('daily_total_routes')->nullable();
            $table->integer('bi_weekly_3_total_routes')->nullable();
            $table->integer('bi_weekly_2_total_routes')->nullable();
            $table->integer('weekly_total_routes')->nullable();
            $table->integer('fortnightly_total_routes')->nullable();
            $table->integer('daily_total_sections')->nullable();
            $table->integer('bi_weekly_3_total_sections')->nullable();
            $table->integer('bi_weekly_2_total_sections')->nullable();
            $table->integer('weekly_total_sections')->nullable();
            $table->integer('fortnightly_total_sections')->nullable();
            $table->string('peripheral_db_east')->nullable();
            $table->string('peripheral_db_west')->nullable();
            $table->string('peripheral_db_north')->nullable();
            $table->string('peripheral_db_south')->nullable();
            $table->string('peripheral_md_east')->nullable();
            $table->string('peripheral_md_west')->nullable();
            $table->string('peripheral_md_north')->nullable();
            $table->string('peripheral_md_south')->nullable();
            $table->string('back_office_team_manager')->nullable();
            $table->string('back_office_team_supervisor')->nullable();
            $table->string('back_office_team_comp_operator')->nullable();
            $table->string('back_office_team_csm')->nullable();
            $table->string('back_office_team_office_clerk')->nullable();
            $table->string('back_office_team_godown_keeper')->nullable();
            $table->string('back_office_team_peon_guards')->nullable();
            $table->string('back_office_team_driver_nmv')->nullable();
            $table->string('back_office_team_others')->nullable();
            $table->string('back_office_team_field_forces')->nullable();
            $table->string('back_office_team_sales_representative')->nullable();
            $table->string('back_office_team_delivery_man')->nullable();
            $table->string('back_office_team_driver_mech_vehicle')->nullable();
            $table->string('back_office_force')->nullable();
            $table->string('total_manpower')->nullable();
            $table->string('logistics_vehicles')->nullable();
            $table->string('logistics_number_of_mv_4wh')->nullable();
            $table->string('logistics_tempoo_3whl')->nullable();
            $table->string('logistics_engine_boat_mv')->nullable();
            $table->string('logistics_number_of_nmv')->nullable();
            $table->string('logistics_total_vehicles')->nullable();
            $table->string('logistics_vehicle_section')->nullable();
            $table->string('logistics_ol_productivity')->nullable();
            $table->string('logistics_route_prod')->nullable();
            $table->string('logistics_section_prod')->nullable();
            $table->string('logistics_route')->nullable();
            $table->string('route_service_mv_route')->nullable();
            $table->string('route_service_nmv_route')->nullable();
            $table->string('outlet_coverage_mv_route')->nullable();
            $table->string('outlet_coverage_nmv_route')->nullable();
            $table->string('route_productivity_mv_route')->nullable();
            $table->string('route_productivity_nmv_route')->nullable();
            $table->integer('total_routes')->nullable();
            $table->string('leverage_it')->nullable();
            $table->string('computer')->nullable();
            $table->string('printer')->nullable();
            $table->string('warehouse_address')->nullable();
            $table->string('warehouse_district')->nullable();
            $table->string('warehouse_thana')->nullable();
            $table->string('office_hight')->nullable();
            $table->string('warehouse_hight')->nullable();
            $table->string('hight_total')->nullable();
            $table->string('office_length')->nullable();
            $table->string('warehouse_length')->nullable();
            $table->string('length_total')->nullable();
            $table->string('workspace_structure_office')->nullable();
            $table->string('warehouse_structure_length')->nullable();
            $table->string('warehouse_condition')->nullable();
            $table->string('electrical_wiring')->nullable();
            $table->string('insurance_coverage')->nullable();
            $table->string('insurance_coverage_office')->nullable();
            $table->string('insurance_coverage_warehouse')->nullable();
            $table->string('team_sitting_arrangement')->nullable();
            $table->string('fire_fighting_facilities')->nullable();
            $table->string('investment_capabilities')->nullable();
            $table->string('self_finance')->nullable();
            $table->string('loan')->nullable();
            $table->string('working_capital')->nullable();
            $table->string('stock_value')->nullable();
            $table->string('credit_to_trade')->nullable();
            $table->string('cash_in_hand')->nullable();
            $table->string('pending_claims')->nullable();
            $table->string('mechanized_vehicle')->nullable();
            $table->string('non_mechanized_vehicle')->nullable();
            $table->string('office_furniture_equipment')->nullable();
            $table->string('total_investment')->nullable();
            $table->string('wc_to')->nullable();
            $table->string('stock_days_cover')->nullable();
            $table->string('stock_salt')->nullable();
            $table->string('stock_flour')->nullable();
            $table->string('stock_oil')->nullable();
            $table->string('stock_rice')->nullable();
            $table->string('stock_pulse')->nullable();
            $table->string('stock_tea')->nullable();
            $table->string('stock_dairy')->nullable();
            $table->string('investment_stock')->nullable();
            $table->string('investment_to')->nullable();
            $table->string('distributor_bank_name')->nullable();
            $table->string('bank_account_number')->nullable();
            $table->string('branch_name')->nullable();
            $table->string('payment_mode')->nullable();
            $table->string('delivery_product')->nullable();
            $table->string('carrying_charge_claimable')->nullable();
            $table->bigInteger('created_by')->nullable();
            $table->bigInteger('updated_by')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('business_information');
    }
};
